/**
 * Generate router using the buildRouter pattern for better type inference
 */
export function generateRouter(opts: {
    basePath: string
    relativeActionsPath: string
}) {
    const { basePath, relativeActionsPath } = opts

    return `import type { HonoEnv } from '@gnosticdev/hono-actions'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import { showRoutes } from 'hono/dev'
import { logger } from 'hono/logger'
import { prettyJSON } from 'hono/pretty-json'
import type { ExtractSchema, MergeSchemaPath } from 'hono/types'

export async function buildRouter(){
    type ActionSchema = ExtractSchema<typeof honoActions[keyof typeof honoActions]>
    const { honoActions} = await import('${relativeActionsPath}')
    const app = new Hono<HonoEnv, MergeSchemaPath<ActionSchema, '${basePath}'>>().basePath('${basePath}')

    app.use('*', cors(), logger(), prettyJSON())

    for (const action of Object.values(honoActions)) {
        app.route('/', action)
    }

    showRoutes(app)
    return app
}

export type HonoRouter = Awaited<ReturnType<typeof buildRouter>>

const app = await buildRouter()
export default app`
}

/**
 * Injects the Hono router into the Astro API route handler at `src/pages/api/[...slug].ts`
 *
 * For use with `@astrojs/cloudflare` adapter only (for now).a
 */
export const getAstroHandler = (adapter: 'cloudflare') => {
    switch (adapter) {
        case 'cloudflare':
            return `
// Generated by Hono Actions Integration
import router from './router.js'
import type { APIContext, APIRoute } from 'astro'

const handler: APIRoute<APIContext> = async (ctx) => {
    return router.fetch(
        ctx.request,
        ctx.locals.runtime.env,
        ctx.locals.runtime.ctx,
    )
}

export { handler as ALL }
`
        default:
            throw new Error(`Unsupported adapter: ${adapter}`)
    }
}
export const getHonoClient = (port: number) => `
// Generated by Hono Actions Integration
import type { HonoRouter } from './router.js'
import { hc } from 'hono/client'

export function getBaseUrl() {
    // client side can just use the base path
    if (typeof window !== 'undefined') {
        return '/'
    }

    // dev server (dev server) needs to know the port
    if (import.meta.env.DEV) {
        return \`http://localhost:\${${port}}\`
    }

    // server side (production) needs full url
    return import.meta.env.SITE
}

export const honoClient = hc<HonoRouter>(getBaseUrl())
`
