name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: bun
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run --cwd package build

      - name: Create Release Pull Request or Publish
        id: changesets
        if: ${{ github.event_name == 'push' }}
        uses: changesets/action@v1
        with:
          version: bun run --cwd package ci:version
          publish: bun run --cwd package ci:publish
          commit: "[ci] release"
          title: "[ci] release"
        env:
          # Needs the repo permissions
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
          # Needs access to publish to npm
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}